### ISSUE TITLE
Reference Error: Window not defined

### ISSUE THREAD

**Issue by guyhamilton** [geosigno/simpleParallax.js#40] opened 2020-02-26 21:58 UTC
Hi, great plugin! I installed via NPM and followed the setup guide but am getting the below error, any ideas?

`ReferenceError: window is not defined
    at Object.<anonymous> (/node_modules/simple-parallax-js/dist/simpleParallax.min.js:7:227)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/gulpfile.js:41:24)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
192-168-1-8:$ gulp
/node_modules/simple-parallax-js/dist/simpleParallax.min.js:7
!function(t,e){"object"==typeof exports&&"object"==typeof module?module.exports=e():"function"==typeof define&&define.amd?define("simpleParallax",[],e):"object"==typeof exports?exports.simpleParallax=e():t.simpleParallax=e()}(window,(function(){return function(t){var e={};function n(i){if(e[i])return e[i].exports;var s=e[i]={i:i,l:!1,exports:{}};return t[i].call(s.exports,s,s.exports,n),s.l=!0,s.exports}return n.m=t,n.c=e,n.d=function(t,e,i){n.o(t,e)||Object.defineProperty(t,e,{enumerable:!0,get:i})},n.r=function(t){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(t,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(t,"__esModule",{value:!0})},n.t=function(t,e){if(1&e&&(t=n(t)),8&e)return t;if(4&e&&"object"==typeof t&&t&&t.__esModule)return t;var i=Object.create(null);if(n.r(i),Object.defineProperty(i,"default",{enumerable:!0,value:t}),2&e&&"string"!=typeof t)for(var s in t`

**Comment by geosigno** [comment] 2020-02-27 11:11
Hi,

Could you please copy paste here the JS you are using to import it?

**Comment by kgnbuchanan** [comment] 2020-03-04 19:41
Hey there, I'm also getting a window undefined error on production builds. Using Gatsby, it errors out with just the import, no additional code.

**Comment by geosigno** [comment] 2020-03-05 11:03
I'm unable to reproduce that issue sor far... which version of webpack are you using?

**Comment by StefanoVuerich** [comment] 2020-04-11 20:21
Hi, I think the problem is not with sampleParallax, but with Gatby itself.

Try use somethink like this for production build:

`if (typeof window !== 'undefined') {
			new window.simpleParallax(//ref, {
				//config
			});
}`

**Comment by geosigno** [comment] 2020-04-17 05:29
I close this issue for now as it seems to be related to Gatsby. If not, please re-open it.

**Closed by geosigno** 2020-04-17 05:29 UTC

**Comment by roboturnerdev** [comment] 2021-11-11 05:53
I am not using Gatsby and experiencing this issue.

**Comment by missfelic** [comment] 2023-01-09 12:10
Can you do something like importing the package inside of the typeof window check?

```
if (window !== 'undefined') {
 const SimpleParallax = require('simple-parallax-js');
 new SimpleParallax(image);
}
```
